-- Baseline schema for user management.
--
-- The unique constraint on email is what makes duplicate detection a real
-- guarantee: an application-level "does this email exist?" check alone is
-- race-prone under concurrent requests.
--
-- varchar(320) is the maximum length of an email address per RFC 5321
-- (64-character local part + "@" + 255-character domain).

create table users (
    id         bigint       generated by default as identity primary key,
    first_name varchar(100) not null,
    last_name  varchar(100) not null,
    email      varchar(320) not null,

    constraint uq_users_email unique (email)
);
