-- The unique constraint makes duplicate detection a real guarantee; an
-- application-level check alone is race-prone under concurrent requests.
-- varchar(320) is the maximum email length per RFC 5321 (64 + "@" + 255).

create table users (
    id         bigint       generated by default as identity primary key,
    first_name varchar(100) not null,
    last_name  varchar(100) not null,
    email      varchar(320) not null,

    constraint uq_users_email unique (email)
);
